<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	
	<PackageId>JobRunner.Quartz</PackageId>
    <Version>1.0.6</Version>
    <Authors>Mello41</Authors>
    <Description>Quartz.NET implementation for JobRunner</Description>
    <RepositoryUrl></RepositoryUrl>
    <PackageTags>jobrunner;tasks;scheduler;background;jobs;domain;core</PackageTags>
	
    <PackageReadmeFile>README.Quartz.md</PackageReadmeFile>
	
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
	
    <MinVerSkip>true</MinVerSkip>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.Quartz.md" Pack="true" PackagePath="\" />
    <None Include="icon.Quartz.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
    <PackageReference Include="Quartz" Version="3.18.0" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.18.0" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.0" />
  </ItemGroup>

  <ItemGroup>
  <!-- при публикации PackageReference, при разработке ProjectReference -->
	<ProjectReference Include="..\JobRunner.Core\JobRunner.Core.csproj" />
	
    <!-- 
    <PackageReference Include="JobRunner.Core" Version="1.0.10" />
    -->
  </ItemGroup>

</Project>
