<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
	
	<PackageId>JobRunner.Core</PackageId>
    <Version>1.0.5</Version>
    <Authors>Mello41</Authors>
    <Description>Core domain models and interfaces for JobRunner</Description>
    <RepositoryUrl></RepositoryUrl>
    <PackageTags>jobrunner;tasks;scheduler</PackageTags>
	
    <MinVerSkip>true</MinVerSkip>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Text.Json" Version="6.0.11" />
  </ItemGroup>

</Project>
